env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  no-unexpected-multiline: error
  react/react-in-jsx-scope: off
  semi: off
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/consistent-type-definitions": ["error", "interface"]
  "@typescript-eslint/semi": ["error", "always"]
settings:
  "import/resolver":
    typescript: {}
